export { Home } from './Home';
export { ProductDetails } from './ProductDetails';
export { Cart } from './Cart';
export { Checkout } from './Checkout';
export { Catalog } from './Catalog';
export { Favorites } from './Favorites';
export { Recipients } from './Recipients';
export { Inbox } from './Inbox';
export { Account } from './Account';
